language: c
os:
    - osx
    - linux
compiler:
    - clang
    - gcc
env:
    - BUILD_TYPE="Release"
    - BUILD_TYPE="Debug"
matrix:
  include:
    - compiler: i586-mingw32msvc-gcc
      env: OPTIONS="-DWIN32=ON -DMINGW=ON"
      os: linux
  allow_failures:
    - compiler: i586-mingw32msvc-gcc
script:
    - mkdir _build
    - cd _build
    - cmake -DCMAKE_INSTALL_PREFIX="../_install" -DCMAKE_BUILD_TYPE="$BUILD_TYPE" $OPTIONS ..
    - cmake --build . --use-stderr
    - cmake --build . --target install
